services:
  # --- PERSISTENCIA (Base de Datos) ---
  postgres:
    image: postgres:15
    container_name: nexus-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"

  # --- CACHÉ Y RATE LIMITING ---
  redis:
    image: redis:7-alpine
    container_name: nexus-cache
    ports:
      - "6379:6379"

  # --- MENSAJERÍA (Kafka con KRaft, sin Zookeeper para simplicidad) ---
  kafka:
    image: apache/kafka:latest
    container_name: nexus-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  # --- SEGURIDAD (Keycloak) ---
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: nexus-auth
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  # --- OBSERVABILIDAD (Opcional inicial para Kibana/Elastic) ---
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: nexus-search
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: nexus-viz
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch